//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace April25Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rezultat", Namespace="http://schemas.datacontract.org/2004/07/April25")]
    [System.SerializableAttribute()]
    public partial class Rezultat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IzrazField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VrednostField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Izraz {
            get {
                return this.IzrazField;
            }
            set {
                if ((object.ReferenceEquals(this.IzrazField, value) != true)) {
                    this.IzrazField = value;
                    this.RaisePropertyChanged("Izraz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Vrednost {
            get {
                return this.VrednostField;
            }
            set {
                if ((this.VrednostField.Equals(value) != true)) {
                    this.VrednostField = value;
                    this.RaisePropertyChanged("Vrednost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IKalkulator", CallbackContract=typeof(April25Client.ServiceReference1.IKalkulatorCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IKalkulator {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulator/ObrisiRacunanje")]
        void ObrisiRacunanje();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulator/ObrisiRacunanje")]
        System.Threading.Tasks.Task ObrisiRacunanjeAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulator/Dodaj")]
        void Dodaj(decimal broj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulator/Dodaj")]
        System.Threading.Tasks.Task DodajAsync(decimal broj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulator/Oduzmi")]
        void Oduzmi(decimal broj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulator/Oduzmi")]
        System.Threading.Tasks.Task OduzmiAsync(decimal broj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulator/Pomnozi")]
        void Pomnozi(decimal broj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulator/Pomnozi")]
        System.Threading.Tasks.Task PomnoziAsync(decimal broj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulator/Podeli")]
        void Podeli(decimal broj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulator/Podeli")]
        System.Threading.Tasks.Task PodeliAsync(decimal broj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKalkulatorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulator/Rezultat")]
        void Rezultat([System.ServiceModel.MessageParameterAttribute(Name="rezultat")] April25Client.ServiceReference1.Rezultat rezultat1);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulator/Greska")]
        void Greska(string poruka);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKalkulatorChannel : April25Client.ServiceReference1.IKalkulator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KalkulatorClient : System.ServiceModel.DuplexClientBase<April25Client.ServiceReference1.IKalkulator>, April25Client.ServiceReference1.IKalkulator {
        
        public KalkulatorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public KalkulatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public KalkulatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public KalkulatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public KalkulatorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ObrisiRacunanje() {
            base.Channel.ObrisiRacunanje();
        }
        
        public System.Threading.Tasks.Task ObrisiRacunanjeAsync() {
            return base.Channel.ObrisiRacunanjeAsync();
        }
        
        public void Dodaj(decimal broj) {
            base.Channel.Dodaj(broj);
        }
        
        public System.Threading.Tasks.Task DodajAsync(decimal broj) {
            return base.Channel.DodajAsync(broj);
        }
        
        public void Oduzmi(decimal broj) {
            base.Channel.Oduzmi(broj);
        }
        
        public System.Threading.Tasks.Task OduzmiAsync(decimal broj) {
            return base.Channel.OduzmiAsync(broj);
        }
        
        public void Pomnozi(decimal broj) {
            base.Channel.Pomnozi(broj);
        }
        
        public System.Threading.Tasks.Task PomnoziAsync(decimal broj) {
            return base.Channel.PomnoziAsync(broj);
        }
        
        public void Podeli(decimal broj) {
            base.Channel.Podeli(broj);
        }
        
        public System.Threading.Tasks.Task PodeliAsync(decimal broj) {
            return base.Channel.PodeliAsync(broj);
        }
    }
}
