
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 01 17:00:45 CET 2024
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GEQ = 27;
  public static final int AND = 13;
  public static final int ELSE = 11;
  public static final int OR = 12;
  public static final int EQUAL = 24;
  public static final int SEMI = 17;
  public static final int CHAR = 7;
  public static final int WHILE = 10;
  public static final int LEFTPAR = 20;
  public static final int END = 5;
  public static final int GREATER = 26;
  public static final int RIGHTPAR = 21;
  public static final int COLON = 18;
  public static final int ID = 14;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 4;
  public static final int BOOLEAN = 9;
  public static final int COMMA = 19;
  public static final int EOF = 0;
  public static final int CONST = 15;
  public static final int error = 1;
  public static final int DOT = 3;
  public static final int ASSIGN = 16;
  public static final int LEQ = 23;
  public static final int INTEGER = 6;
  public static final int REAL = 8;
  public static final int NEQ = 25;
  public static final int LESS = 22;
}

