//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vlasnik", Namespace="http://schemas.datacontract.org/2004/07/Jun24")]
    public partial class Vlasnik : object
    {
        
        private string ImeField;
        
        private string JmbgField;
        
        private string PrezimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime
        {
            get
            {
                return this.ImeField;
            }
            set
            {
                this.ImeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jmbg
        {
            get
            {
                return this.JmbgField;
            }
            set
            {
                this.JmbgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime
        {
            get
            {
                return this.PrezimeField;
            }
            set
            {
                this.PrezimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Skladiste", Namespace="http://schemas.datacontract.org/2004/07/Jun24")]
    public partial class Skladiste : object
    {
        
        private decimal CenaField;
        
        private int IdSkladisteField;
        
        private System.DateTime KrajZakupaField;
        
        private System.DateTime PocetakZakupaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cena
        {
            get
            {
                return this.CenaField;
            }
            set
            {
                this.CenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSkladiste
        {
            get
            {
                return this.IdSkladisteField;
            }
            set
            {
                this.IdSkladisteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime KrajZakupa
        {
            get
            {
                return this.KrajZakupaField;
            }
            set
            {
                this.KrajZakupaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PocetakZakupa
        {
            get
            {
                return this.PocetakZakupaField;
            }
            set
            {
                this.PocetakZakupaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zakup", Namespace="http://schemas.datacontract.org/2004/07/Jun24")]
    public partial class Zakup : object
    {
        
        private ServiceReference2.Skladiste SkladisteField;
        
        private ServiceReference2.Vlasnik VlasnikField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Skladiste Skladiste
        {
            get
            {
                return this.SkladisteField;
            }
            set
            {
                this.SkladisteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Vlasnik Vlasnik
        {
            get
            {
                return this.VlasnikField;
            }
            set
            {
                this.VlasnikField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IZakupSkladista")]
    public interface IZakupSkladista
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladista/ZakupiSkladiste", ReplyAction="http://tempuri.org/IZakupSkladista/ZakupiSkladisteResponse")]
        void ZakupiSkladiste(ServiceReference2.Vlasnik vlasnik, ServiceReference2.Skladiste skladiste);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladista/ZakupiSkladiste", ReplyAction="http://tempuri.org/IZakupSkladista/ZakupiSkladisteResponse")]
        System.Threading.Tasks.Task ZakupiSkladisteAsync(ServiceReference2.Vlasnik vlasnik, ServiceReference2.Skladiste skladiste);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladista/VratiAktivnaSkladistaVlasnika", ReplyAction="http://tempuri.org/IZakupSkladista/VratiAktivnaSkladistaVlasnikaResponse")]
        ServiceReference2.Skladiste[] VratiAktivnaSkladistaVlasnika(string jmbg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladista/VratiAktivnaSkladistaVlasnika", ReplyAction="http://tempuri.org/IZakupSkladista/VratiAktivnaSkladistaVlasnikaResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Skladiste[]> VratiAktivnaSkladistaVlasnikaAsync(string jmbg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladista/VratiVlasnikeAktivnihSkladista", ReplyAction="http://tempuri.org/IZakupSkladista/VratiVlasnikeAktivnihSkladistaResponse")]
        ServiceReference2.Vlasnik[] VratiVlasnikeAktivnihSkladista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladista/VratiVlasnikeAktivnihSkladista", ReplyAction="http://tempuri.org/IZakupSkladista/VratiVlasnikeAktivnihSkladistaResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Vlasnik[]> VratiVlasnikeAktivnihSkladistaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladista/VratiIstorijuZakupa", ReplyAction="http://tempuri.org/IZakupSkladista/VratiIstorijuZakupaResponse")]
        ServiceReference2.Zakup[] VratiIstorijuZakupa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladista/VratiIstorijuZakupa", ReplyAction="http://tempuri.org/IZakupSkladista/VratiIstorijuZakupaResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Zakup[]> VratiIstorijuZakupaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IZakupSkladistaChannel : ServiceReference2.IZakupSkladista, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ZakupSkladistaClient : System.ServiceModel.ClientBase<ServiceReference2.IZakupSkladista>, ServiceReference2.IZakupSkladista
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZakupSkladistaClient() : 
                base(ZakupSkladistaClient.GetDefaultBinding(), ZakupSkladistaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IZakupSkladista.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZakupSkladistaClient(EndpointConfiguration endpointConfiguration) : 
                base(ZakupSkladistaClient.GetBindingForEndpoint(endpointConfiguration), ZakupSkladistaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZakupSkladistaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZakupSkladistaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZakupSkladistaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZakupSkladistaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZakupSkladistaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void ZakupiSkladiste(ServiceReference2.Vlasnik vlasnik, ServiceReference2.Skladiste skladiste)
        {
            base.Channel.ZakupiSkladiste(vlasnik, skladiste);
        }
        
        public System.Threading.Tasks.Task ZakupiSkladisteAsync(ServiceReference2.Vlasnik vlasnik, ServiceReference2.Skladiste skladiste)
        {
            return base.Channel.ZakupiSkladisteAsync(vlasnik, skladiste);
        }
        
        public ServiceReference2.Skladiste[] VratiAktivnaSkladistaVlasnika(string jmbg)
        {
            return base.Channel.VratiAktivnaSkladistaVlasnika(jmbg);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Skladiste[]> VratiAktivnaSkladistaVlasnikaAsync(string jmbg)
        {
            return base.Channel.VratiAktivnaSkladistaVlasnikaAsync(jmbg);
        }
        
        public ServiceReference2.Vlasnik[] VratiVlasnikeAktivnihSkladista()
        {
            return base.Channel.VratiVlasnikeAktivnihSkladista();
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Vlasnik[]> VratiVlasnikeAktivnihSkladistaAsync()
        {
            return base.Channel.VratiVlasnikeAktivnihSkladistaAsync();
        }
        
        public ServiceReference2.Zakup[] VratiIstorijuZakupa()
        {
            return base.Channel.VratiIstorijuZakupa();
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Zakup[]> VratiIstorijuZakupaAsync()
        {
            return base.Channel.VratiIstorijuZakupaAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IZakupSkladista))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IZakupSkladista))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:61806/ZakupSkladista.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ZakupSkladistaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IZakupSkladista);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ZakupSkladistaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IZakupSkladista);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IZakupSkladista,
        }
    }
}
