
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 08 11:49:23 CET 2024
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GEQ = 25;
  public static final int OCTCONST = 28;
  public static final int AND = 13;
  public static final int ELSE = 11;
  public static final int OR = 12;
  public static final int EQUAL = 22;
  public static final int CHAR = 7;
  public static final int SEMI = 15;
  public static final int WHILE = 10;
  public static final int LEFTPAR = 18;
  public static final int END = 5;
  public static final int GREATER = 24;
  public static final int RIGHTPAR = 19;
  public static final int COLON = 16;
  public static final int HEXCONST = 29;
  public static final int ID = 26;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 4;
  public static final int BOOLEAN = 9;
  public static final int COMMA = 17;
  public static final int EOF = 0;
  public static final int CHARCONST = 31;
  public static final int REALCONST = 30;
  public static final int error = 1;
  public static final int DOT = 3;
  public static final int DECCONST = 27;
  public static final int ASSIGN = 14;
  public static final int LEQ = 21;
  public static final int INTEGER = 6;
  public static final int REAL = 8;
  public static final int NEQ = 23;
  public static final int LESS = 20;
}

